### ISSUE TITLE
[Question] Wireshark and Sensniff 

### ISSUE THREAD

**Issue by nguyenduclam** [g-oikonomou/sensniff#9]
Hello, 
I do not mean to post its as an issue, however I have some troubles with using Wireshark to capture packet with sensniff. 
Scenario: 
I run the command: 
**:~/sensniff$ sudo python sensniff.py -d /dev/ttyUSB0 -D INFO
Started logging
Serial port /dev/ttyUSB0 opened
FIFO /tmp/sensniff exists. Using it
Commands:
c: Print current RF Channel
m: Print Min RF Channel
M: Print Max RF Channel
n: Trigger new pcap header before the next frame
h,?: Print this message
<number>: Change RF channel.
q: Quit
Sent bytes: c1 1f fe 72 02 81 
Peripheral: x<�x<�x�x������x�x<x��x��x<��x��x��x���x��x��x�x<x��x��x<�x�x�x�x<���x**

And then, when I use wireshark to capture on /tmp/sensniff, however it's not work. Wireshark can not capture any packet or anything. 
Can you give me some feedbacks to solve this problem? 
I run  /contiki/example/ipv6/rpl-tsch/rpl-tsch.c and flash it into OpenMote-CC2538. 
Wireshark version which I use is provided by OpenWSN webpage. 
Thank you very much. 
Lam.

**Comment by g-oikonomou** [comment]
You _are_ running the correct sniffer firmware on the openmote, right?

**Comment by nguyenduclam** [comment]
Thanks for your response, 
I am wondering that, 
For example: 
I have 4Openmote nodes {**3 OpenMote-Openbatery nodes**  AND **1 OpenMote-OpenBase node**}
In which, 
+ 3 OpenMote-OpenBatery nodes run RPL-TSCH protocol.
+ we need to have 1 OpenMote-OpenBase which connect to PC through serial connection, and in this node, we flash sniffer firmware (contiki/example/cc2538dk/sniffer.c) into OpenMote. 
And then, we start Wireshark and capture packets through serial connection between 1 OpenMote-OpenBase and PC ? . 
If I was wrong, please correct me since I am very new in Contiki,OpenMote. 
Thank you very much. 
Lam.

**Comment by g-oikonomou** [comment]
OK that's clear. You are using a very old version of Contiki. 

Two things you can do:

* Either use latest version of Contiki: sniffer firmware under `examples/cc2538-common`
* Or use the example from my recent Contiki pull request: https://github.com/contiki-os/contiki/pull/1795

In all cases, make sure to run sensniff with the correct -b argument. Default in latest version is 460800, you may need to switch to the baud rate output by your openmote. This is commonly the cause for garbage characters such as the ones you are seeing.

Just to clarify, sensniff is not very suitable to capture TSCH traffic, since TSCH channel-hops all the time, whereas sensniff only captures a single channel

**Comment by nguyenduclam** [comment]
Thank you very much for your useful information,

Lam.
